# Generated by Django 3.2 on 2022-01-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamentos',
            fields=[
                ('sigla', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('afastamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'afastamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AfastamentosProfessores',
            fields=[
                ('data_in', models.DateField(primary_key=True, serialize=False)),
                ('data_fn', models.DateField(blank=True, null=True)),
                ('aulas', models.IntegerField(blank=True, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'afastamentos_professores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anos',
            fields=[
                ('ano', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'anos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('carg_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('disc_id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disciplinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('jorn_id', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jornadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('prof_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.CharField(blank=True, max_length=1, null=True)),
                ('efetivo', models.CharField(blank=True, max_length=1, null=True)),
                ('adm', models.DateField(blank=True, null=True)),
                ('desl', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('sede_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sedes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessoresAulas',
            fields=[
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='faltas.professores')),
                ('ha_al', models.IntegerField(blank=True, null=True)),
                ('ha_htp', models.IntegerField(blank=True, null=True)),
                ('supl', models.IntegerField(blank=True, null=True)),
                ('outr', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('faul', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professores_aulas',
                'managed': False,
            },
        ),
    ]
